### ISSUE TITLE
Triangle Mesh Loading

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/Klampt#204]
AssimpImporter throws an error when trying to load geometries from the GRAB dataset for some reason. `trimesh` seems to load them successfully.

Versions:
- Ubuntu 20.04
- Python 3.8.20
- Klampt 0.10.0
- libassimp-dev 5.0.1~ds0-1build1

Minimum example:
```python
import klampt
import trimesh

world = klampt.WorldModel()
ro = world.makeRigidObject("obj")
ro.geometry().loadFile("flashlight.ply")

trimesh.load("flashlight.ply")
```

The klampt load throws
```
AssimpImporter error: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 26) while loading flashlight.ply
AssimpImporter error: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 26) while loading flashlight.ply
Import(TriMesh): file flashlight.ply
ManagedGeometry: Error loading geometry file flashlight.ply
```

while trimesh loads fine.

Attaching the flashlight.ply mesh (as well as another example mesh, airplane.ply).

[meshes.zip](https://github.com/user-attachments/files/19236598/meshes.zip)

**Comment by krishauser** [comment]
Following up on this, is this fixed with a different Assimp version?

**Comment by patricknaughton01** [comment]
Weirdly still getting the same error on a different machine:

- Ubuntu 22.04
- Python: 3.12.9
- klampt: 0.10.0
- libassimp-dev: 5.3.1+ds-2build1

Same error message:
```
AssimpImporter error: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 26) while loading flashlight.ply
AssimpImporter error: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 26) while loading flashlight.ply
Import(TriMesh): file flashlight.ply
ManagedGeometry: Error loading geometry file flashlight.ply
```

Still seems like an Assimp bug and/or some weirdness with these particular meshes. I tried installing Assimp 5.2.2 but ran into some issues that look like they have to do with compatibility with other system libraries (like zip?).

**Comment by krishauser** [comment]
Fixed by pinning specific version of assimp. Will be available in pip shortly
